name: Build android common kernel
on:
  push:
    branches: [ "android12-5.10-2022-01" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Package For Build
      run: |
        sudo apt update && sudo apt install -y curl liblz4-1 libyaml-0-2 p7zip-full gcc g++ bison bc make git zip flex zipalign libssl-dev python3 gcc-aarch64-linux-gnu cpio tree

    - name: Download Build Tools
      run: |
        cd $GITHUB_WORKSPACE
        pwd
        tree -L 2
        git clone https://gerrit.googlesource.com/git-repo
        mkdir android-kernel && cd android-kernel
        ../git-repo/repo init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-android12-5.10-2022-01
        ../git-repo/repo sync
        cd common
        git checkout --orphan android12-5.10-2022-01
        git rm -rf .
        git pull https://github.com/huazhaozhe/android_gki_kernel_5.10_common_xaga.git android12-5.10-2022-01

    - name: Build Kernel
      run: |
        cd $GITHUB_WORKSPACE/android-kernel
        pwd
        tree -L 2
        LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh

    - name: Build Kernel Package
      run: |
        VERSION="GKI-5.10-$(date '+%Y-%m%d-%H%M')"
        cd $GITHUB_WORKSPACE
        pwd
        tree -L 2
        git clone https://github.com/zzh-zzh-zzh/AnyKernel3.git -b GKI --depth=1
        cp android-kernel/out/android12-5.10/dist/Image AnyKernel3
        cd AnyKernel3
        7z a -mx9 tmp.zip *
        zipalign -v 4 tmp.zip ../$VERSION.zip
        rm tmp.zip
        
    - name: Upload Image
      uses: actions/upload-artifact@v3
      with:
        path: GKI-5.10-*.zip